
--Q1
SELECT TOP 1 C.BRAND_CODE,SUM(A.TOTAL_SPENT) AS DOLLARS_SPENT FROM RECEIPTS A 
JOIN RECEIPT_ITEMS B ON A.ID=B.REWARDS_RECEIPT_ID
JOIN brands$ C ON B.BRAND_CODE=C.BRAND_CODE
WHERE DATEPART(MONTH,A.PURCHASE_DATE)=6
GROUP BY C.BRAND_CODE
ORDER BY SUM(A.TOTAL_SPENT) DESC



--Q2
SELECT TOP 1 USER_ID,SUM(TOTAL_SPENT) AS TOTAL_SPENT_BY_MONTH FROM receipts
WHERE DATEPART(MONTH,PURCHASE_DATE)=8
GROUP BY USER_ID
ORDER BY SUM(TOTAL_SPENT) DESC

--Q3
SELECT TOP 1 A.USER_ID,A.ID AS RECEIPT_ID,B.REWARDS_RECEIPT_ITEM_ID AS ITEM_ID,SUM(TOTAL_FINAL_PRICE)/SUM(QUANTITY_PURCHASED) AS ITEM_COST
FROM RECEIPTS A LEFT JOIN RECEIPT_ITEMS B 
ON A.ID=B.REWARDS_RECEIPT_ID
GROUP BY A.USER_ID,A.ID,B.REWARDS_RECEIPT_ITEM_ID
HAVING SUM(QUANTITY_PURCHASED)>0
ORDER BY SUM(TOTAL_FINAL_PRICE)/SUM(QUANTITY_PURCHASED) DESC

--Q4

SELECT TOP 1 A.USER_ID,A.ID AS RECEIPT_ID,B.REWARDS_RECEIPT_ITEM_ID AS ITEM_ID,B.BRAND_CODE,C.NAME AS ITEM_NAME,SUM(TOTAL_FINAL_PRICE)/SUM(QUANTITY_PURCHASED) AS ITEM_COST
FROM RECEIPTS A LEFT JOIN RECEIPT_ITEMS B 
ON A.ID=B.REWARDS_RECEIPT_ID
LEFT JOIN [dbo].[brands$] C
ON B.BRAND_CODE=C.BRAND_CODE
GROUP BY A.USER_ID,A.ID,B.REWARDS_RECEIPT_ITEM_ID,B.BRAND_CODE,C.NAME
HAVING SUM(QUANTITY_PURCHASED)>0
ORDER BY SUM(TOTAL_FINAL_PRICE)/SUM(QUANTITY_PURCHASED) DESC

--Q5
SELECT DATEPART(YEAR,DATE_SCANNED) YEAR_OF_SCANNED,
DATEPART(MONTH,DATE_SCANNED) MONTH_OF_SCAN,
COUNT(DISTINCT USER_ID) AS NUMBER_OF_USERS
FROM receipts
GROUP BY 
DATEPART(YEAR,DATE_SCANNED),
DATEPART(MONTH,DATE_SCANNED)
ORDER BY
DATEPART(YEAR,DATE_SCANNED) DESC,
DATEPART(MONTH,DATE_SCANNED)


